server:
  port: 8763
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-ha-node1:8761/eureka/,http://eureka-server-ha-node2:8771/eureka/
