server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server  自己本身就是Eureka Server 所以不需要
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息  自己本身就是注Eureka Server 所以不需要
    fetchRegistry: false
    serviceUrl:
      #注册服务的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server